name: k8s

services:
  # =========================
  # Registry Docker Local
  # =========================
  registry:
    image: registry:3.1.1
    container_name: k8s-registry

    ports:
      - 5000:5000

    volumes:
      - registry-data:/var/lib/registry

    networks:
      - k8s

  # =========================
  # Control Plane
  # =========================
  cp:
    image: rancher/k3s:v1.36.4-k3s1
    container_name: k8s-cp
    privileged: true

    environment:
      K3S_TOKEN: mon-super-token-secret

    ports:
      - 8080:80
      # - 5000:32647

    volumes:
      - k3s-server:/var/lib/rancher/k3s
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml

    networks:
      - k8s

    command:
      - server
      - --node-taint=node-role.kubernetes.io/control-plane=true:NoSchedule

  # =========================
  # Worker 1
  # =========================
  worker1:
    image: rancher/k3s:v1.36.4-k3s1
    container_name: k8s-worker1
    privileged: true

    environment:
      K3S_TOKEN: mon-super-token-secret
      K3S_URL: https://cp:6443

    volumes:
      - k3s-worker1:/var/lib/rancher/k3s
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml

    networks:
      - k8s

    depends_on:
      - cp

    command:
      - agent


  # =========================
  # Worker 2
  # =========================
  worker2:
    image: rancher/k3s:v1.36.4-k3s1
    container_name: k8s-worker2
    privileged: true

    environment:
      K3S_TOKEN: mon-super-token-secret
      K3S_URL: https://cp:6443

    volumes:
      - k3s-worker2:/var/lib/rancher/k3s
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml

    networks:
      - k8s

    depends_on:
      - cp

    command:
      - agent


  # =========================
  # Worker 3
  # =========================
  worker3:
    image: rancher/k3s:v1.36.4-k3s1
    container_name: k8s-worker3
    privileged: true

    environment:
      K3S_TOKEN: mon-super-token-secret
      K3S_URL: https://cp:6443

    volumes:
      - k3s-worker3:/var/lib/rancher/k3s
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml

    networks:
      - k8s

    depends_on:
      - cp

    command:
      - agent


networks:
  k8s:
    name: k8s

volumes:
  registry-data:
  k3s-server:
  k3s-worker1:
  k3s-worker2:
  k3s-worker3:
