spring.application.name = demo

spring.jpa.open-in-view = false

server.servlet.context-path = /api
server.shutdown = immediate
server.forward-headers-strategy = framework

spring.mvc.problemdetails.enabled = true

spring.datasource.url = jdbc:postgresql://db/iia
spring.datasource.username = iia
spring.datasource.password = O44r'<06GMh4A}![Lu9U;30t<zi#

spring.jpa.show-sql = true
spring.jpa.generate-ddl = true
