apiVersion: v1
kind: Secret

metadata:
  name: app-node-secret

# data:
#   MAVARIABLE: bGUgc2VjcmV0Cg== # en base64

stringData:
  MAVARIABLE: le secret en clair
  var_name_different: autre valeur differente

  MYSQL_ROOT_PASSWORD: root2
  MYSQL_USERNAME: root
