apiVersion: apps/v1 # On adapte la version en fonction du type d'API
kind: Deployment # Le type d'API

metadata:
  name: app-node

spec:
  replicas: 2 # Nombre de réplicas

  selector:
    matchLabels:
      app: app-node # Gestion des pods qui ont ce label

  template:
    metadata:
      labels:
        app: app-node # Tout ce qu'on a mis dans le selector doit se trouver ici

    spec:
      containers:
        - name: app-node
          image: registry:5000/app-node:v3
          imagePullPolicy: Always # On force le pull à chaque changement

          ports:
            - containerPort: 80

          envFrom: # configMapRef et secretRef sont bien sûr cumulables
            - configMapRef:
                name: app-node-config

            - secretRef:
                name: app-node-secret

          env:
            - name: MAVARIABLE
              valueFrom:
                secretKeyRef:
                  name: app-node-secret
                  key: var_name_different

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-node-config
                  key: MYSQL_HOSTNAME

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-node-config
                  key: MYSQL_DATABASE

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-node-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-node-secret
                  key: MYSQL_USERNAME

          # env:
          #   - name: MAVARIABLE
          #     value: Jeremy