name: hello-compose

services:
  db:
    container_name: hello-db
    image: postgres:18.6-alpine3.23
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: eac6d01745de4ad7ced8f2a8452086e9b085ddfb9a4fe0d510144594ea274476
      POSTGRES_DB: hello

    networks:
      - hello

    volumes:
      - db-data:/var/lib/postgresql/18/docker

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "hello" ]
      timeout: 3s
      retries: 10
      interval: 5s

  flyway:
    container_name: hello-flyway
    image: flyway/flyway:13.7

    environment:
      FLYWAY_URL: jdbc:postgresql://db/hello
      FLYWAY_USER: hello
      FLYWAY_PASSWORD: eac6d01745de4ad7ced8f2a8452086e9b085ddfb9a4fe0d510144594ea274476

    volumes:
      - ./migrations:/flyway/sql

    depends_on:
      db:
        condition: service_healthy

    networks:
      - hello

    command:
      - migrate

  boot:
    image: hello-spring
    container_name: hello-boot

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/hello
      SPRING_DATASOURCE_USERNAME: hello
      SPRING_DATASOURCE_PASSWORD: eac6d01745de4ad7ced8f2a8452086e9b085ddfb9a4fe0d510144594ea274476

    depends_on:
      flyway:
        condition: service_completed_successfully

    ports:
      - 8080:8080

    networks:
      - hello

volumes:
  db-data:
    name: hello-db-data

networks:
  hello:
    name: hello
